#include "music_streams.hpp"

namespace Music {
  const std::array<StreamSlot, BGM_COUNT> streamSlots = {{
      /* 00 */ {nullptr,                                       "General Sfx",                   rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 01 */ {nullptr,                                       "Ambience",                      rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 02 */ {"002NA_BGM_FIELD.dspadpcm.bcstm",              "Termina Field",                 rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 03 */ {"003NA_BGM_CHASE.dspadpcm.bcstm",              "Chase",                         rnd::SEQ_BGM_BATTLE, true, kNoLink},
      /* 04 */ {"004NA_BGM_STALKID.dspadpcm.bcstm",            "Majoras Theme",                 rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 05 */ {"005NA_BGM_CLOCK_TOWER.dspadpcm.bcstm",        "Clock Tower",                   rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 06 */ {"006NA_BGM_RUIN_DUNGEON_FRONT.dspadpcm.bcstm", "Stone Tower Temple",            rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 07 */ {"007NA_BGM_RUIN_DUNGEON_REVERSE.dspadpcm.bcstm", "Inverted Stone Tower Temple",   rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 08 */ {"008NA_BGM_FAILURE_0.dspadpcm.bcstm",          "Failure 0",                     rnd::SEQ_FANFARE, false, kNoLink},
      /* 09 */ {"009NA_BGM_FAILURE_1.dspadpcm.bcstm",          "Failure 1",                     rnd::SEQ_FANFARE, false, kNoLink},
      /* 0A */ {"010NA_BGM_OMENYA.dspadpcm.bcstm",             "Happy Mask Salesman",           rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 0B */ {"011NA_BGM_DEMO_CURE.dspadpcm.bcstm",          "Song of Healing",               rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 0C */ {"012NA_BGM_DAMP_AREA.dspadpcm.bcstm",          "Swamp Region",                  rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 0D */ {"013NA_BGM_UFO.dspadpcm.bcstm",                "Alien Invasion",                rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 0E */ {nullptr,                                       "Swamp Cruise",                  rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 0F */ {"015NA_BGM_SHARP.dspadpcm.bcstm",              "Sharps Curse",                  rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 10 */ {"016NA_BGM_SEA_AREA.dspadpcm.bcstm",           "Great Bay Region",              rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 11 */ {"017NA_BGM_IKANA_AREA.dspadpcm.bcstm",         "Ikana Region",                  rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 12 */ {"018NA_BGM_DEKU_KING.dspadpcm.bcstm",          "Deku Palace",                   rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 13 */ {"019NA_BGM_SNOW_AREA.dspadpcm.bcstm",          "Mountain Region",               rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 14 */ {"020NA_BGM_PIRATE_AREA.dspadpcm.bcstm",        "Pirates Fortress",              rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 15 */ {"021NA_BGM_DUMMY_21.dspadpcm.bcstm",           "Clock Town Day 1",              rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 16 */ {"022NA_BGM_DUMMY_22.dspadpcm.bcstm",           "Clock Town Day 2",              rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 17 */ {"023NA_BGM_DUMMY_23.dspadpcm.bcstm",           "Clock Town Day 3",              rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 18 */ {"024NA_BGM_FILE_SELECT.dspadpcm.bcstm",        "File Select",                   rnd::SEQ_NOSHUFFLE, true, kNoLink},
      /* 19 */ {"025NA_BGM_EVENT_CLEAR.dspadpcm.bcstm",        "Clear Event",                   rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 1A */ {"026NA_BGM_ENEMY.dspadpcm.bcstm",              "Enemy",                         rnd::SEQ_BGM_BATTLE, true, kNoLink},
      /* 1B */ {"027NA_BGM_BOSS00.dspadpcm.bcstm",             "Boss",                          rnd::SEQ_BGM_BATTLE, true, kNoLink},
      /* 1C */ {"028NA_BGM_JUNGLE_DUNGEON.dspadpcm.bcstm",     "Woodfall Temple",               rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 1D */ {"029NA_BGM_MARKET.dspadpcm.bcstm",             "Clock Town Main Sequence",      rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 1E */ {"030NA_BGM_OPENING.dspadpcm.bcstm",            "Opening",                       rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 1F */ {"031NA_BGM_LINK_HOUSE.dspadpcm.bcstm",         "Inside A House",                rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 20 */ {"032NA_BGM_GAME_OVER.dspadpcm.bcstm",          "Game Over",                     rnd::SEQ_FANFARE, false, kNoLink},
      /* 21 */ {"033NA_BGM_BOSS_CLEAR.dspadpcm.bcstm",         "Clear Boss",                    rnd::SEQ_FANFARE, false, kNoLink},
      /* 22 */ {"034NA_BGM_ITEM_GET.dspadpcm.bcstm",           "Get Item",                      rnd::SEQ_FANFARE, false, kNoLink},
      /* 23 */ {"035NA_BGM_GATE_OPEN.dspadpcm.bcstm",          "Clock Town Day 2 (pointer)",          rnd::SEQ_NOSHUFFLE, true, 0x16},
      /* 24 */ {"036NA_BGM_HEART_GET.dspadpcm.bcstm",          "Get Heart",                     rnd::SEQ_FANFARE, false, kNoLink},
      /* 25 */ {"037NA_BGM_MINI_GAME_2.dspadpcm.bcstm",        "Timed Mini Game",               rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 26 */ {"038NA_BGM_GORON_RACE.dspadpcm.bcstm",         "Goron Race",                    rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 27 */ {"039NA_BGM_ORGEL_HOUSE.dspadpcm.bcstm",        "Music Box House",               rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 28 */ {"040NA_BGM_GODESS.dspadpcm.bcstm",             "Fairy Fountain",                rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 29 */ {"041NA_BGM_HIME.dspadpcm.bcstm",               "Zeldas Lullaby",                rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 2A */ {"042NA_BGM_SISTER_DANCER.dspadpcm.bcstm",      "Rosa Sisters",                  rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 2B */ {"043NA_BGM_OPEN_TRE_BOX.dspadpcm.bcstm",       "Open Chest",                    rnd::SEQ_FANFARE, false, kNoLink},
      /* 2C */ {"044NA_BGM_DRUGSTORE.dspadpcm.bcstm",          "Marine Research Lab",           rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 2D */ {"045NA_BGM_KYOJIN_ROOM.dspadpcm.bcstm",        "Giants Theme",                  rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 2E */ {"046NA_BGM_FUSHA.dspadpcm.bcstm",              "Song of Storms",                rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 2F */ {"047NA_BGM_RONRON.dspadpcm.bcstm",             "Romani Ranch",                  rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 30 */ {"048NA_BGM_GORON.dspadpcm.bcstm",              "Goron Village",                 rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 31 */ {"049NA_BGM_MEETING.dspadpcm.bcstm",            "Mayors Office",                 rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 32 */ {"050NA_BGM_OCA_EPONA.dspadpcm.bcstm",          "Ocarina Epona",                 rnd::SEQ_OCARINA, false, kNoLink},
      /* 33 */ {"051NA_BGM_OCA_SUN.dspadpcm.bcstm",            "Ocarina Suns",                  rnd::SEQ_OCARINA, false, kNoLink},
      /* 34 */ {"052NA_BGM_OCA_TIME_NORMAL.dspadpcm.bcstm",    "Ocarina Time",                  rnd::SEQ_OCARINA, false, kNoLink},
      /* 35 */ {"053NA_BGM_OCA_STORM.dspadpcm.bcstm",          "Ocarina Storm",                 rnd::SEQ_OCARINA, false, kNoLink},
      /* 36 */ {"054NA_BGM_ZORA.dspadpcm.bcstm",               "Zora Hall",                     rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 37 */ {"055NA_BGM_MASK_GET.dspadpcm.bcstm",           "Get New Mask",                  rnd::SEQ_FANFARE, false, kNoLink},
      /* 38 */ {"056NA_BGM_MIDDLE_BOSS.dspadpcm.bcstm",        "Mini Boss",                     rnd::SEQ_BGM_BATTLE, true, kNoLink},
      /* 39 */ {"057NA_BGM_S_ITEM_GET.dspadpcm.bcstm",         "Get Small Item",                rnd::SEQ_FANFARE, false, kNoLink},
      /* 3A */ {"058NA_BGM_TENMONDAI.dspadpcm.bcstm",          "Astral Observatory",            rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 3B */ {"059NA_BGM_NORMAL_DUNGEON.dspadpcm.bcstm",     "Cavern",                        rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 3C */ {nullptr,                                       "Milk Bar",                      rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 3D */ {"061NA_BGM_APPEAR.dspadpcm.bcstm",             "Zelda Appear",                  rnd::SEQ_FANFARE, false, kNoLink},
      /* 3E */ {"062NA_BGM_MAYOIMORI.dspadpcm.bcstm",          "Sarias Song",                   rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 3F */ {"063NA_BGM_GORON_GOAL.dspadpcm.bcstm",         "Goron Goal",                    rnd::SEQ_FANFARE, false, kNoLink},
      /* 40 */ {"064NA_BGM_HORSE.dspadpcm.bcstm",              "Horse",                         rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 41 */ {"065NA_BGM_HORSE_GOAL.dspadpcm.bcstm",         "Horse Goal",                    rnd::SEQ_FANFARE, false, kNoLink},
      /* 42 */ {"066NA_BGM_INGO.dspadpcm.bcstm",               "Ingo",                          rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 43 */ {"067NA_BGM_KOTAKE_KOUME.dspadpcm.bcstm",       "Kotake Potion Shop",            rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 44 */ {nullptr,                                       "Shop",                          rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 45 */ {"069NA_BGM_OWL.dspadpcm.bcstm",                "Owl",                           rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 46 */ {nullptr,                                       "Shooting Gallery",              rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 47 */ {"071NA_BGM_OCA_BIGWING.dspadpcm.bcstm",        "Ocarina Soaring",               rnd::SEQ_OCARINA, false, kNoLink},
      /* 48 */ {"072NA_BGM_OCA_CURE.dspadpcm.bcstm",           "Ocarina Healing",               rnd::SEQ_OCARINA, false, kNoLink},
      /* 49 */ {"073NA_BGM_TIME_SPEED.dspadpcm.bcstm",         "Inverted Song of Time",         rnd::SEQ_OCARINA, false, kNoLink},
      /* 4A */ {"074NA_BGM_TIME_JUMP.dspadpcm.bcstm",          "Song of Double Time",           rnd::SEQ_OCARINA, false, kNoLink},
      /* 4B */ {"075NA_BGM_DEMO_AWAKING.dspadpcm.bcstm",       "Sonata of Awakening",           rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 4C */ {"076NA_BGM_DEMO_LULLABY.dspadpcm.bcstm",       "Goron Lullaby",                 rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 4D */ {"077NA_BGM_DEMO_TIDE.dspadpcm.bcstm",          "New Wave Bossa Nova",           rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 4E */ {"078NA_BGM_DEMO_SHELL.dspadpcm.bcstm",         "Elegy of Emptiness",            rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 4F */ {"079NA_BGM_DEMO_PLEDGE.dspadpcm.bcstm",        "Oath To Order",                 rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 50 */ {"080NA_BGM_EXERCISE_HALL.dspadpcm.bcstm",      "Sword Training Hall",           rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 51 */ {"081NA_BGM_DEMO_LULLABY_HALF.dspadpcm.bcstm",  "Ocarina Lullaby Intro",         rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 52 */ {"082NA_BGM_OCA_YOUSEI.dspadpcm.bcstm",         "Learned New Song",              rnd::SEQ_FANFARE, false, kNoLink},
      /* 53 */ {"083NA_BGM_FACEMASK.dspadpcm.bcstm",           "Bremen March",                  rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 54 */ {"084NA_BGM_QUARTET.dspadpcm.bcstm",            "Ballad of the Wind Fish",       rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 55 */ {"085NA_BGM_WING_WARP.dspadpcm.bcstm",          "Song of Soaring",               rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 56 */ {"086NA_BGM_MILK_BAR_DUMMY.dspadpcm.bcstm",     "Milk Bar Duplicate",            rnd::SEQ_NOSHUFFLE, true, kNoLink},
      /* 57 */ {"087NA_BGM_TIME_LIMIT.dspadpcm.bcstm",         "Final Hours",                   rnd::SEQ_NOSHUFFLE, true, kNoLink},
      /* 58 */ {"088NA_BGM_MIKAU_LIFF.dspadpcm.bcstm",         "Mikau Riff",                    rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 59 */ {"089NA_BGM_MIKAU_FIN.dspadpcm.bcstm",          "Mikau Finale",                  rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 5A */ {"090NA_BGM_FROG_SONG.dspadpcm.bcstm",          "Frog Song",                     rnd::SEQ_NOSHUFFLE, true, kNoLink},
      /* 5B */ {"091NA_BGM_OCA_AWAKING.dspadpcm.bcstm",        "Ocarina Sonata",                rnd::SEQ_OCARINA, false, kNoLink},
      /* 5C */ {"092NA_BGM_OCA_LULLABY.dspadpcm.bcstm",        "Ocarina Lullaby",               rnd::SEQ_OCARINA, false, kNoLink},
      /* 5D */ {"093NA_BGM_OCA_TIDE.dspadpcm.bcstm",           "Ocarina New Wave",              rnd::SEQ_OCARINA, false, kNoLink},
      /* 5E */ {"094NA_BGM_OCA_SHELL.dspadpcm.bcstm",          "Ocarina Elegy",                 rnd::SEQ_OCARINA, false, kNoLink},
      /* 5F */ {"095NA_BGM_OCA_PLEDGE.dspadpcm.bcstm",         "Ocarina Oath",                  rnd::SEQ_OCARINA, false, kNoLink},
      /* 60 */ {"096NA_BGM_LAST_DUNGEON.dspadpcm.bcstm",       "Majoras Lair",                  rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 61 */ {"097NA_BGM_OCA_LULLABY_HALF.dspadpcm.bcstm",   "Ocarina Lullaby Intro (pointer)",     rnd::SEQ_NOSHUFFLE, false, 0x51},
      /* 62 */ {"098NA_BGM_OCA_SESSION.dspadpcm.bcstm",        "Ocarina Guitar Bass Session",   rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 63 */ {"099NA_BGM_DEMO_SESSION.dspadpcm.bcstm",       "Piano Session",                 rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 64 */ {"100NA_BGM_ALLPART_SESSION.dspadpcm.bcstm",    "Indigo Go Session",             rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 65 */ {"101NA_BGM_SILVER_DUNGEON.dspadpcm.bcstm",     "Snowhead Temple",               rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 66 */ {"102NA_BGM_DEEPBLUE_DUNGEON.dspadpcm.bcstm",   "Great Bay Temple",              rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 67 */ {"103NA_BGM_DEMO_TIDE_SAX.dspadpcm.bcstm",      "New Wave Saxophone",            rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 68 */ {"104NA_BGM_DEMO_TIDE_VOCAL.dspadpcm.bcstm",    "New Wave Vocal",                rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 69 */ {"105NA_BGM_MUJURA_1.dspadpcm.bcstm",           "Majoras Wrath",                 rnd::SEQ_BGM_BATTLE, true, kNoLink},
      /* 6A */ {"106NA_BGM_MUJURA_2.dspadpcm.bcstm",           "Majoras Incarnation",           rnd::SEQ_BGM_BATTLE, true, kNoLink},
      /* 6B */ {"107NA_BGM_MUJURA_3.dspadpcm.bcstm",           "Majoras Mask",                  rnd::SEQ_BGM_BATTLE, true, kNoLink},
      /* 6C */ {"108NA_BGM_BASS_PLAY.dspadpcm.bcstm",          "Bass Play",                     rnd::SEQ_NOSHUFFLE, true, kNoLink},
      /* 6D */ {"109NA_BGM_DRUMS_PLAY.dspadpcm.bcstm",         "Drums Play",                    rnd::SEQ_NOSHUFFLE, true, kNoLink},
      /* 6E */ {"110NA_BGM_PIANO_PLAY.dspadpcm.bcstm",         "Piano Play",                    rnd::SEQ_NOSHUFFLE, true, kNoLink},
      /* 6F */ {"111NA_BGM_IKANA_CASTLE.dspadpcm.bcstm",       "Ikana Castle",                  rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 70 */ {"112NA_BGM_GATHERING.dspadpcm.bcstm",          "Gathering Giants",              rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 71 */ {"113NA_BGM_CAMARO_DANCE.dspadpcm.bcstm",       "Kamaro Dance",                  rnd::SEQ_NOSHUFFLE, true, kNoLink},
      /* 72 */ {"114NA_BGM_DONKEY_CART.dspadpcm.bcstm",        "Cremia Carriage",               rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 73 */ {"115NA_BGM_QUIZ.dspadpcm.bcstm",               "Keaton Quiz",                   rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 74 */ {"116NA_BGM_END_DEMO.dspadpcm.bcstm",           "End Credits",                   rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 75 */ {"117NA_BGM_OPENING_LOOP.dspadpcm.bcstm",       "Opening Loop",                  rnd::SEQ_NOSHUFFLE, true, kNoLink},
      /* 76 */ {"118NA_BGM_TITLE.dspadpcm.bcstm",              "Title Theme",                   rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 77 */ {"119NA_BGM_DUNGEON_APPEAR.dspadpcm.bcstm",     "Dungeon Appear",                rnd::SEQ_FANFARE, false, kNoLink},
      /* 78 */ {"120NA_BGM_PURIFICATION_0.dspadpcm.bcstm",     "Woodfall Clear",                rnd::SEQ_FANFARE, false, kNoLink},
      /* 79 */ {"121NA_BGM_PURIFICATION_1.dspadpcm.bcstm",     "Snowhead Clear",                rnd::SEQ_FANFARE, false, kNoLink},
      /* 7A */ {nullptr,                                       "Unused 122",                    rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 7B */ {"123NA_BGM_INTO_THE_MOON.dspadpcm.bcstm",      "Into the Moon",                 rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 7C */ {"124NA_BGM_GOODBYE_GIANT.dspadpcm.bcstm",      "Goodbye Giant",                 rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 7D */ {"125NA_BGM_CHAT.dspadpcm.bcstm",               "Tatl And Tael",                 rnd::SEQ_BGM_EVENT, true, kNoLink},
      /* 7E */ {"126NA_BGM_MOON_VANISH.dspadpcm.bcstm",        "Moons Destruction",             rnd::SEQ_BGM_EVENT, false, kNoLink},
      /* 7F */ {"127NA_BGM_OCA_MUS.dspadpcm.bcstm",            "End Credits Second Half",       rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 80 */ {nullptr,                                       "Demo Se Seq Old",               rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 81 */ {"129NA_BGM_FISHING1.dspadpcm.bcstm",           "Fishing1",                      rnd::SEQ_BGM_WORLD, true, kNoLink},
      /* 82 */ {nullptr,                                       "Staffroll2",                    rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 83 */ {nullptr,                                       "M Barquartet",                  rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 84 */ {nullptr,                                       "M Barquartet All",              rnd::SEQ_NOSHUFFLE, false, kNoLink},
      /* 85 */ {nullptr,                                       "Zora Session",                  rnd::SEQ_NOSHUFFLE, false, kNoLink},
  }};
  static_assert(streamSlots.size() == BGM_COUNT);

  const char* CategoryFolder(rnd::SeqType category) {
    switch (category) {
      case rnd::SEQ_BGM_WORLD:  return "Area Themes";
      case rnd::SEQ_BGM_BATTLE: return "Battle Themes";
      case rnd::SEQ_BGM_EVENT:  return "Event Themes";
      case rnd::SEQ_FANFARE:    return "Fanfares";
      case rnd::SEQ_OCARINA:    return "Ocarina Songs";
      default:                  return nullptr;
    }
  }
}  // namespace Music
